theme: jekyll-theme-slate
title: Beatriz Gonzalez Mellidez
description: This is both my presentation card and my sandbox, so if something doesn't work, feel free to let me know: maybe i was having too much fun with the tools!
